---
title: "Carbonate reanalysis"
author: "Brett Longworth"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Reanalysis of carbonate data with most current data reduction method.

```{r}
library(tidyverse)
library(here)
library(amstools)
library(hgis)

theme_set(theme_bw())
options(digits = 3)
options(scipen = 4)
```

Run analysis script

```{r}
source(here("R/analyse_carbonates.R"))
```

Plot raw data

```{r}
map(results, 1) %>% 
  map(plot_hgis_time, y_var = norm_ratio, outlier = ok_calc)
```

```{r}
map(results, 1) %>% 
  map(plot_hgis_time, y_var = he12C, outlier = ok_calc)
```

```{r}
results_df %>% 
  filter(!is.na(rec_num),
         sample_type == "B") %>% 
  select(sample_name, rec_num, wheel, sample_type, fm_consensus, fm_corr, sig_fm_corr) %>% 
  arrange(pos)
```

```{r}
results_df %>% 
  filter(!is.na(rec_num),
         !is.na(sig_fm_corr)) %>% 
  compare_replicates() %>% 
  arrange(rec_num) %>% 
  select(Name, N)
```

```{r}
cons_df <- compare_consensus(results_df)

cons_df %>% 
  select(wheel, pos, sample_name, fm_consensus, fm_corr, sig_fm_corr, fm_diff, sigma) %>% 
  arrange(desc(fm_diff))
```
  
```{r}
cons_df %>% 
  filter(wheel != "USAMS020521") %>% 
plot_hgis_consensus()
```
  
```{r}
cons_df %>% 
  filter(wheel != "USAMS020521") %>% 
  group_by(Name, fm_consensus) %>% 
  summarize(across(c(fm_corr, sig_fm_corr, fm_diff, sigma), list(mean = mean, sd = sd)))
```

```{r}
cons_df %>% 
  ungroup() %>% 
  filter(wheel != "USAMS020521") %>% 
  summarize(across(c(sig_fm_corr, fm_diff, sigma), list(mean = mean, sd = sd)))
```
